name: Setup Runtime and Dependencies

inputs:
  token:
    description: 'The GitHub/npm token'
    required: true
    type: string
  working-directory:
    description: 'The path to the directory to run commands'
    required: false
    type: string
    default: ./
  fetch-depth:
    description: Number of commits to fetch. 0 indicates all history for all branches and tags.
    required: false
    type: string
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{inputs.fetch-depth}}

    - name: Setup node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/
        scope: '@openphone'

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      env:
        lockfile-path: ${{inputs.working-directory}}/package-lock.json
      with:
        path: ~/.npm
        key: modules-${{hashFiles(format('{0}/package-lock.json', inputs.working-directory))}}

    - name: Run CI
      run: npm ci
      working-directory: ${{inputs.working-directory}}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{inputs.token}}
