name: 'Setup Matrix'
description: 'Setup a test matrix'

inputs:
  shard_count:
    description: 'Number of shards'
    required: false
    default: '1'
outputs:
  shards:
    description: 'The test matrix shards'
    value: ${{ steps.set-matrix.outputs.shards }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: set-matrix
      shell: pwsh
      run: setup-matrix.ps1
      env:
        shard_count: ${{ inputs.shard_count }}
