name: Set Version And Publish

inputs:
  version:
    description: 'The version to set in package.json and publish'
    required: true
    type: string
  token:
    description: 'The GitHub/npm token'
    required: true
    type: string
  working-directory:
    description: 'The path to the directory to run commands'
    required: false
    type: string
    default: ./

runs:
  using: "composite"
  steps:
    - name: Set Version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm version "${{ inputs.version }}" --no-git-tag-version --no-commit-hooks --allow-same-version

    - name: Publish
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
