name: Build Application

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com/
          scope: '@openphone'

      - uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
            path: ./node_modules
            key: modules-${{ hashFiles('package-lock.json') }}

      - name: Run CI
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.token}}

      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build
      - run: node .
