name: Build Client

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true

jobs:
  getver:
    uses: OpenPhone/gha/.github/workflows/getver.yml@v4

  build-client:
    name: Build and Publish Client
    runs-on: ubuntu-22.04
    needs: getver
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Setup
        uses: OpenPhone/gha/.github/actions/setup@v4
        with:
          token: ${{ secrets.token }}

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm node .

      - name: Publish
        uses: OpenPhone/gha/.github/actions/publish@v4
        with:
          token: ${{ inputs.token }}
          version: ${{ needs.getver.outputs.version }}
