name: Build Application

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true

jobs:
  getver:
    uses: OpenPhone/gha/.github/workflows/getver.yml@common-actions

  build-types:
    name: Build and Publish Types
    runs-on: ubuntu-22.04
    needs: getver
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: ./types
    steps:
      - name: Build
        uses: OpenPhone/gha/.github/workflows/build-typescript-project-types.yml@common-actions

      - name: Publish
        uses: OpenPhone/gha/.github/actions/publish@common-actions
        with:
          token: ${{ inputs.token }}
          version: ${{ needs.getver.outputs.version }}
