name: Build Application

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: OpenPhone/gha/.github/actions/setup@v4
        with:
          token: ${{ secrets.token }}

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Run
        run: node .
