name: Build Application

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true

jobs:
  getver:
    uses: OpenPhone/gha/.github/workflows/getver.yml@v4

  build:
    name: Build and Publish Types
    runs-on: ubuntu-22.04
    needs: getver
    if: github.event_name == 'push'
    steps:
      - name: Build
        uses: OpenPhone/gha/.github/workflows/build-typescript-project.yml@v4

      - name: Publish
        uses: OpenPhone/gha/.github/actions/publish@v4
        with:
          token: ${{ inputs.token }}
          version: ${{ needs.getver.outputs.version }}
