name: Build Types

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true

jobs:
  build-types:
    name: Build Types
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./types
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com/
          scope: '@openphone'
          cache: npm
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.token}}
      - run: npm run build
      - run: npm run test
