name: Build and push docker image

on:
  workflow_call:
    secrets:
      password:
        description: 'password / token for login to container registry'
        required: true
      build_args:
        description: 'Extra build args to give docker build'
        required: false
    inputs:
      registry:
        description: 'Registry to login / push to'
        default: 'ghcr.io'
        required: false
        type: string
      registry_path:
        description: 'Path to registry image name'
        required: true
        type: string
        default: 'openphone/gha'
      dockerfile:
        description: 'Dockerfile you want to build'
        required: true
        type: string
      platforms:
        description: 'Platforms to build for'
        default: 'linux/amd64'
        required: false
        type: string
      tags:
        description: 'Tag for docker image'
        default: 'latest'
        required: false
        type: string
      username:
        description: 'Username to login with'
        default: ${{ github.repository_owner }}
        required: false
        type: string
      update_json:
        description: Update package.json and package-lock.json with tag
        default: false
        required: false
        type: boolean

jobs:
  publish-docker:
    name: Build and push docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update json
        if: ${{ inputs.update_json }}
        run: |
          ver=${{ inputs.tags }}
          jq ".version = \"$ver\"" < package.json > package.up
          mv package.up package.json
          jq ".version = \"$ver\"" < package-lock.json > package-lock.up
          mv package-lock.up package-lock.json
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile}}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.registry_path }}:${{ inputs.tags }}
          build-args: ${{ secrets.build_args }}
