name: Build and push docker image

on:
  workflow_call:
    secrets:
      password:
        required: true
      build-args:
        required: false
    inputs:
      registry:
        default: 'ghcr.io'
        required: false
        type: string
      registry_path:
        required: true
        type: string
        default: 'openphone/gha'
      dockerfile:
        required: true
        type: string
      platforms:
        default: 'linux/amd64'
        required: false
        type: string
      tags:
        default: 'latest'
        required: false
        type: string
      username:
        default: ${{ github.repository_owner }}
        required: false
        type: string

jobs:
  publish-docker:
    name: Build and push docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile}}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.registry_path }}:${{ inputs.tags }}
          build-args: ${{ inputs.build-args }}
