name: Get Version from Tag

on:
  workflow_call:
    outputs:
      version:
        description: 'The version of the current tag'
        value: ${{jobs.getver.outputs.version}}

jobs:
  getver:
    name: Get Version
    runs-on: ubuntu-latest

    outputs:
      version: ${{steps.vertag.outputs.version}}

    steps:
      - id: vertag
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
