name: Manual workflow
on:
  workflow_dispatch:

jobs:
  test_workflow:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: OpenPhone/gha
          ref: main
          token: ${{ secrets.GHA_CR_PAT }}
          path: ./.github/workflows
      - name: Run my action
        uses: ./.github/workflows/super-linter.yml
        with:
          linter-branch: 'master'

  do_stuff:
    runs-on: ubuntu-20.04
    steps: 
      - name: "Do Stuff"
        env:
          GITHUB_PAYLOAD: ${{ toJson(github) }}
        run: |
          echo "repo: ${{ github.repository }}"
          echo "sha: ${{ github.sha }}"
          echo "github ref: ${{ github.ref }}"
          echo "github ref_name: ${{ github.ref_nam }}"
          echo "github_actor: ${{ github.actor }}"
          echo ${GITHUB_PAYLOAD}
