name: Manual workflow
on:
  workflow_dispatch:

jobs:
  test_workflow:
    runs-on: ubuntu-20.04
    steps:
      - name: Run superlinter
        uses: OpenPhone/gha/.github/workflows/superlinter.yml@main
        with:
          linter-branch: 'main'

  do_stuff:
    runs-on: ubuntu-20.04
    steps: 
      - name: "Do Stuff"
        env:
          GITHUB_PAYLOAD: ${{ toJson(github) }}
        run: |
          echo "repo: ${{ github.repository }}"
          echo "sha: ${{ github.sha }}"
          echo "github ref: ${{ github.ref }}"
          echo "github ref_name: ${{ github.ref_nam }}"
          echo "github_actor: ${{ github.actor }}"
          echo ${GITHUB_PAYLOAD}
