name: Manual workflow
on:
  workflow_dispatch:

jobs:
  do_stuff:
    runs-on: ubuntu-20.04
    steps: 
      - run: |
          echo "repo: ${{ github.repository }}"
          echo "sha: ${{ github.sha }}"
          echo "github ref: ${{ github.ref }}
          echo "github ref_name: ${{ github.ref_nam }}
          echo "github_actor: ${{ github.actor }}
          echo "github: ${{ toJson(github) }}
