name: Reusable workflow for running elastic for integration tests

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true
    inputs:
      test_command:
        description: 'The command to run the integration tests'
        default: 'npm run test:ci'
        required: false
        type: string
      elastic_password:
        description: 'The Elastic password'
        default: 'changeme'
        required: false
        type: string
      elastic_url:
        description: 'The Elastic host url'
        default: 'http://localhost:9200'
        required: false
        type: string
      working-directory:
        description: 'The path to the directory to run commands'
        required: false
        type: string
        default: ./

jobs:
  test-integration-elastic:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
        env:
          STACK_VERSION: 8.1.2
          ELASTIC_PASSWORD: ${{ inputs.elastic_password }}
          discovery.type: single-node
          xpack.security.enabled: false
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Setup
        uses: OpenPhone/gha/.github/actions/setup@v4
        with:
          token: ${{ secrets.token }}
          working-directory: ${{inputs.working-directory}}
      - run: npm run elastic:up
        env:
          ELASTIC_URL: ${{ inputs.elastic_url }}
          ELASTIC_PASSWORD: ${{ inputs.elastic_password }}
      - run: ${{ inputs.test_command }} # Test all the things!!!
        env:
          ENVIRONMENT: test
          ELASTIC_URL: ${{ inputs.elastic_url }}
          ELASTIC_PASSWORD: ${{ inputs.elastic_password }}
      - uses: codecov/codecov-action@v3
