name: Reusable workflow for running mongo integration tests

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true
    inputs:
      test_command:
        description: 'The command to run the integration tests'
        default: 'npm run test:ci'
        required: false
        type: string
      mongo_version:
        description: 'The version of Mongo to use'
        default: '4.2'
        required: false
        type: string
      mongo_username:
        description: 'The Mongo username'
        default: 'admin'
        required: false
        type: string
      mongo_password:
        description: 'The Mongo password'
        default: 'docker'
        required: false
        type: string
      mongo_db:
        description: 'The Mongo db name'
        default: 'openphone'
        required: false
        type: string

jobs:
  test-integration-mongo:
    runs-on: ubuntu-latest

    steps:
      - uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ inputs.mongo_version }}
          mongodb-username: ${{ inputs.mongo_username }}
          mongodb-password: ${{ inputs.mongo_password }}
          mongodb-db: ${{ inputs.mongo_db }}
      - uses: actions/checkout@v2
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.token }}
      - run: ${{ inputs.test_command }}
        env:
          ENVIRONMENT: test
      - name: Codecov Uploader
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
