name: Reusable workflow for running postgres integration tests

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true
    inputs:
      migration_command:
        description: 'The command to run the Postgres migrations'
        default: 'npm run db:up'
        required: false
        type: string
      test_command:
        description: 'The command to run the integration tests'
        default: 'npm run test:ci'
        required: false
        type: string
      postgres_version:
        description: 'The version of Postgres to use'
        default: '13'
        required: false
        type: string
      postgres_user:
        description: 'The Postgres user'
        default: 'openphone'
        required: false
        type: string
      postgres_password:
        description: 'The Postgres password'
        default: 'docker'
        required: false
        type: string
      postgres_host:
        description: 'The Postgres host'
        default: 'localhost'
        required: false
        type: string

jobs:
  test-integration-postgres:
    runs-on: ubuntu-latest

    services:
      postgres-svc:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ inputs.postgres_user }}
          POSTGRES_PASSWORD: ${{ inputs.postgres_password }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@openphone'
      - uses: actions/checkout@v2
        with:
          path: 'repo'
      - run: npm ci
        working-directory: 'repo'
        env:
          NODE_AUTH_TOKEN: ${{secrets.token}}
      - run: ${{inputs.migration_command}}
        working-directory: 'repo'
        env:
          ENVIRONMENT: test
          POSTGRES_HOST: ${{ inputs.postgres_host }}
      - run: ${{inputs.test_command}}
        working-directory: 'repo'
        env:
          ENVIRONMENT: test
          POSTGRES_HOST: ${{ inputs.postgres_host }}
