name: Reusable workflow for running integration tests with no external persistence dependencies

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub/npm token'
        required: true
    inputs:
      test_command:
        description: 'The command to run the integration tests'
        default: 'npm run test:ci'
        required: false
        type: string
      working-directory:
        description: 'The path to the directory to run commands'
        required: false
        type: string
        default: ./
      timeout-minutes:
        description: 'The max time to allow the action to run'
        required: false
        type: number
        default: 10

jobs:
  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }} 

    steps:
      - name: Setup
        uses: OpenPhone/gha/.github/actions/setup@v5
        with:
          token: ${{ secrets.token }}
          working-directory: ${{inputs.working-directory}}
      - run: ${{ inputs.test_command }}
        env:
          ENVIRONMENT: test
      - name: Codecov Uploader
        uses: codecov/codecov-action@v3
